### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Pashnik/PackRLE#1]
1. Стоит выдавать ошибку, если не указана ни одна из опций -z или -u.
1. Если имя выходного файла не задано, то оно должно отличаться от имени входного файла добавлением расширения, например, `.out`.
1. Для хранения состояния лучше использовать `enum`, а не просто `int`.
1. Вы пытаетесь сжать одинаковые последовательности длиной до 99 символов, а при декодировании считаете, что максимальное число повторов - 9.
1. Если в конце у Вас состояние 3, то лучше закодировать символ как `1X`, а не `-1X`, так Вы сэкономите 1 символ.
1. Методы `encode` и `decode`можно сделать статическими, так как они не используют поля класса. Кроме того, кодирование/декодирование строки вполне осмысленная операция и может потребоваться пользователю Вашего класса, так что ничего не мешает сделать её публичной, тогда можно будет её протестировать.
1. Протестировать нужно все методы, в том числе `coding` и `decoding`, но так как Вы протестировали `encode` и `decode`, то тестирование `coding` и `decoding` может быть не таким полным, просто проверьте, что они правильно работают с файлами.

**Comment by Pashnik** [comment]
Спасибо за замечания. Все исправил

**Comment by maximpetrov** [comment]
1. Функция `main` не должна выбрасывать исключения, она должна их по возможности отлавливать и выдавать пользователю понятные сообщения об ошибках. Хотя Вам лучше просто вместо выбрасывания исключения об отсутствии режима, вывести сообщение об ошибке и выйти. А ещё неплохо бы в этом случае и в остальных случаях обнаружения ошибки в методе `launch` делать не просто `return`, а `System.exit` с ненулевым кодом.
1. Она из причин использовать `enum` - избавится от "магических чисел", значение которых может быть не очень понятно. От чисел Вы избавились, но сильно понятнее не стало, назовите Ваши состояния как-нибудь осмысленно, а не `STATE_1` и т.д.

**Comment by maximpetrov** [comment]
Принято
